### ISSUE TITLE
Stop action from bubbling on click

### ISSUE THREAD

**Issue by devotox** [st-h/ember-content-editable#19]
is it possible to stop the action from bubbling up on click. 

In my scenario i have the whole element also clickable for another action as i am using this component within another component

**Comment by chrissloey** [comment]
What action do you want to stop bubbling? The component doesn't implement any on click actions.

If you're handling an action that you want to stop bubbling then you should be able to return false to stop it propagating. Not sure if that helps?

**Comment by devotox** [comment]
Yes the problem is that to get into your component to start editing. One would have to click or tap in there . This then causes on on click handler that i have on the outside component to trigger. I have used a roundabout jquery way to in my outer component to stop the propagation of this like so 

```

	afterRenderEvent() {
		this.$().on('click', '.content[contenteditable="true"]', event => {
			event.stopImmediatePropagation();
		});
	},
```

what i was wondering is if you could in your component. stop the initial click action that is needed to start editing from bubbling up to any outer elements?

**Comment by chrissloey** [comment]
Ok, thanks for clarifying. I'd like to preserve the current behaviour as the default rather than defaulting to swallowing actions - I think that should be explicit.

I would accept a PR to make the component accept a custom click action in the same way it does for other actions. I think a good compromise would be for the component to automatically stop propagation if `click=null` is passed instead of `click=action`.

**Comment by devotox** [comment]
```
  click(event) {
    this.sendAction('click', this, event);
  },
```

It should just have been as easy as that but it seems click events are not registering at all on the component
