### ISSUE TITLE
Adhere to data-down, actions-up?

### ISSUE THREAD

**Issue by danidr** [st-h/ember-content-editable#43]
Hello, it's me again, your nightmare.
So, I am implementing a page with the following code:
`{{content-editable value=(get object key) focus-out=(action (mut (get object key)) value='value')}}`
According to the latest standards for Ember helpers, setting `value = (get object key)` should be one-way, and the value should be passed back upon editing only if set with the `mut` helper (`value=(mut (get object key))`).
Instead, editing the content-editable content automatically updates also the variable on the parent component set through `value`, breaking the DDAU paradigm.
My workaround is wrapping the `(get object key)` in a `concat` helper which joins strings, effectively making it a computed variable and therefore not updatable upon editing; but it is quite an ugly hack.
Any reason why content-editable behaves this way?
Thanks,

Daniel

**Comment by st-h** [comment]
yes, I am aware that we are not following DDAU. One reason is that one is able to easily replace the ember input helpers, which behave in exactly the same way (might be case that I missed something since some 1.x release though). Second one is that I don't want to introduce any breaking changes which can be avoided. 
However, I understand that there might be a need for one way bound components. Do you have an idea what changes are needed to make it work the way you describe? from the input helpers it seems like this should be possible to do in a non breaking fashion? 
I mainly found a lot of contradicting posts (some even from the ember team) and blogs about this subject. Things like the mut helper should pass in a mutable object to the component, which should have an update method. However, when accessing the property from the component I don't get a mutable object back. If I access it using the `attrs` hash, I can get the mutable object, but I also get a warning that this is no longer the right way to do things: https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-attrs-in-components.md
I don't think just stopping to modify the `value` will be the right thing to do, so I am kind of at a loss here what actually is the right way to do things right now, as the guides or the api docs don't seem to be very helpful here. Do you a link which describes the mentioned latest standards for ember helpers?
BTW: PRs are very welcome

**Comment by st-h** [comment]
Going to close this issue due to the lack of activity. The wanted behaviour seems to be easily achieved using helpers. Please see [this](http://emberup.co/bindings-with-htmlbars-helpers/) article. Furthermore I could not find any trace regarding the mentioned "latest standards for Ember helpers" after quite a search, nor do I see any way to make this happen except by using deprecated features (as mentioned in my previous reply), as neither `this.get('value')`, nor `this.value` provide any distinction regarding immutabilty of the passed object.

Please feel free to provide further information and I will reopen. I also asekd about this issue on ember slack and will update accordingly in case there will be any further useful information.

**Comment by danidr** [comment]
@st-h,
Forgive me, I have been very busy with other projects! Well, "latest standards" is perhaps a wrong phrasing, I was referring to the latest common practices which use DDAU throughout template helpers.
I will definitely look up that article once I get back on this project.
Thank you in the meanwhile,

Daniele

**Comment by st-h** [comment]
@danidr yes, if you can find anything on how this should be implemented, this would be really helpful. The only related thing I could find is [this deprecated addon](https://github.com/DockYard/ember-one-way-controls). Still, looking at the implementation, this looks more like a lot of complexity rather than doing it the ember way™
I also tried to see how the ember input elements work, but still failed to find anything useful regarding this issue. In the end I set up [this twiddle](https://ember-twiddle.com/ecbfaaab07f6ec95278e149a25b33ada?openFiles=templates.application.hbs%2C) to try to reproduce the desired behaviour you were describing. It looks like the ember helper show the same behaviour as this addon currently does. `{{input value=(get this 'v')}}` directly modifies `this.v`. 

Could you please clarify if this actually is the issue you were reporting?
if yes, could you please explain why we should move away from the behaviour ember seems to currently show?
if no, could you please clarify this issue?

**Comment by danidr** [comment]
Well, in fact, that add-on doesn't look like a good solution... a good idea would be having a look at the implementation of native `input` helpers in the ember code base, but again, time isn't helping, on my side... :(
What I was doing was `{{input value=(concat (get this 'v'))}}`; being `concat` a read-only helper, any attempt to modify it will simply be ignored by the helper itself, that's how I have been able to attain a DDAU-like implementation. But it's clearly an ugly hack.

**Comment by st-h** [comment]
Actually, I am not really able to fully understand your post.

- First off: The ember input helpers behave in the same way as this add on does.
- The `readonly` helper offers a clean way to do what you are trying to accomplish. Please read the links from my previous posts.
- And lastly, I discussed this issue on the dev-ember channel in slack to find out what generally is expected from an addon these days. The summarise that shortly, for most input helpers strictly adhering to DDAU does not make much sense. Secondly, unless angle bracket components has landed, the `readonly` helper offers a clean way to make anything work DDAU style (as already mentioned). In case this behaviour changes when angle bracket components land, we can see if there is a need to make changes to this addon. `value=(get object key)` currently is mutable by default.

In the end, as far as I am able to currently understand this issue: 
- this addon does adhere to the current ember best practises
- Everything you want to do, should be absolutely doable in a clean way right now (using the `readonly` helper)

Unless anything changes due to new ember releases, I am considering this issue closed. In case it should not be, please provide a way to reproduce your actual issue. And lastly, in case there really is a dire need for things to change, please submit a PR.

**Comment by danidr** [comment]
Well, you didn't mention the `readonly` helper anywhere in your previous posts... I did not know about this helper, but it's good to know there is one, therefore I'll use it instead of the ugly `concat` workaround.
About the standard behavior of `input` helpers, I was probably wrong then. If that's the case, leave the code as-is of course.
Until next time,

Daniele

**Comment by st-h** [comment]
For your convenience, this is the article I mentioned a few posts ago regarding the `readonly` helper:

> The wanted behaviour seems to be easily achieved using helpers. Please see [this](http://emberup.co/bindings-with-htmlbars-helpers/) article. 

happy coding
